#!/bin/bash
set -e
openwisp-qa-check \
  --migration-path ./django_netjsonconfig/migrations \
  --migration-module django_netjsonconfig

jslint django_netjsonconfig/static/django-netjsonconfig/js/*.js
