# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 15:43
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0010_basemodel_reorganization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='config',
            field=jsonfield.fields.JSONField(blank=True, default=dict, help_text='configuration in NetJSON DeviceConfiguration format', verbose_name='configuration'),
        ),
    ]
