# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 15:43

import collections
import jsonfield.fields
from django.db import migrations
import collections


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0010_basemodel_reorganization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='config',
            field=jsonfield.fields.JSONField(blank=True, default=dict, dump_kwargs={'ensure_ascii': False, 'indent': 4}, help_text='configuration in NetJSON DeviceConfiguration format', load_kwargs={'object_pairs_hook': collections.OrderedDict}, verbose_name='configuration'),
        ),
    ]
