# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 10:42
from __future__ import unicode_literals

from django.db import migrations

from django_netjsonconfig.models.config import get_random_mac


def randomize_mac_address(apps, schema_editor):
    Config = apps.get_model('django_netjsonconfig', 'Config')
    for c in Config.objects.all():
        c.mac_address = get_random_mac()
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0013_config_mac_address'),
    ]

    operations = [
        migrations.RunPython(randomize_mac_address, reverse_code=migrations.RunPython.noop),
    ]
