# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0018_openvpn_disabled_attr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'template', 'verbose_name_plural': 'templates'},
        ),
        migrations.AlterModelOptions(
            name='vpn',
            options={'verbose_name': 'VPN server', 'verbose_name_plural': 'VPN servers'},
        ),
        migrations.AlterModelOptions(
            name='vpnclient',
            options={'verbose_name': 'VPN client', 'verbose_name_plural': 'VPN clients'},
        ),
        migrations.AlterField(
            model_name='config',
            name='vpn',
            field=models.ManyToManyField(blank=True, related_name='vpn_relations', through='django_netjsonconfig.VpnClient', to='django_netjsonconfig.Vpn'),
        ),
    ]
