# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0023_template_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='model',
            field=models.CharField(blank=True, help_text='device model and manufacturer', max_length=64),
        ),
        migrations.AddField(
            model_name='config',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='config',
            name='os',
            field=models.CharField(blank=True, help_text='operating system identifier', max_length=128, verbose_name='operating system'),
        ),
    ]
