# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0025_populate_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_netjsonconfig.Device'),
        ),
    ]
