# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 14:04

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0030_device_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(db_index=True, help_text='primary mac address', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$', 32), code='invalid', message='Must be a valid mac address.')]),
        ),
    ]
