# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 08:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_netjsonconfig.utils
import re


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0030_device_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='key',
            field=models.CharField(db_index=True, default=django_netjsonconfig.utils.get_random_key, help_text='unique device key', max_length=64, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'^[^\\s/\\.]+$'), code=b'invalid', message='Key must not contain spaces, dots or slashes.')]),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(db_index=True, help_text='primary mac address', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})'), code=b'invalid', message='Must be a valid mac address.')]),
        ),
    ]
