# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0031_auto_20170726_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='backend',
            field=models.CharField(choices=[(b'netjsonconfig.OpenWrt', b'OpenWRT/LEDE'), (b'netjsonconfig.OpenWisp', b'OpenWISP Firmware 1.x'), (b'netjsonconfig.AirOs', b'AirOS v8.3')], help_text='Select <a href="http://netjsonconfig.openwisp.org/en/stable/" target="_blank">netjsonconfig</a> backend', max_length=128, verbose_name='backend'),
        ),
        migrations.AlterField(
            model_name='template',
            name='backend',
            field=models.CharField(choices=[(b'netjsonconfig.OpenWrt', b'OpenWRT/LEDE'), (b'netjsonconfig.OpenWisp', b'OpenWISP Firmware 1.x'), (b'netjsonconfig.AirOs', b'AirOS v8.3')], help_text='Select <a href="http://netjsonconfig.openwisp.org/en/stable/" target="_blank">netjsonconfig</a> backend', max_length=128, verbose_name='backend'),
        ),
    ]
