# Generated by Django 2.0.5 on 2018-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0033_migrate_last_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='management_ip',
            field=models.GenericIPAddressField(blank=True, help_text='ip address of the management interface, if available', null=True),
        ),
    ]
