# Generated by Django 2.0.9 on 2018-10-25 13:02

from django.db import migrations, models

from .. import settings as app_settings


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0035_renamed_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hardware_id',
            field=models.CharField(**(app_settings.HARDWARE_ID_OPTIONS)),
        ),
    ]
