# Generated by Django 2.0.9 on 2018-11-19 07:16

import collections
import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0036_device_hardware_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='context',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'ensure_ascii': False, 'indent': 4}, help_text='Additional <a href="http://netjsonconfig.openwisp.org/en/stable/general/basics.html#context" target="_blank">context (configuration variables)</a> in JSON format', load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True),
        ),
    ]
