# Generated by Django 2.0.9 on 2018-11-19 07:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_netjsonconfig', '0036_device_hardware_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='context',
            field=jsonfield.fields.JSONField(blank=True, help_text='Additional <a href="http://netjsonconfig.openwisp.org/en/stable/general/basics.html#context">context</a> for the configuration.', null=True),
        ),
    ]
